import { EventEmitter } from 'node:events';

export const simulationEvents = new EventEmitter();

export const GameEventNames = {
  RESOURCE_GATHERED: 'RESOURCE_GATHERED',
  CHUNK_RENDERED: 'CHUNK_RENDERED', // Maybe not needed in backend, or used for chunk loading
  RESOURCE_STATE_CHANGE: 'RESOURCE_STATE_CHANGE',
  LEGEND_UPDATE: 'LEGEND_UPDATE',
  REPUTATION_UPDATED: 'REPUTATION_UPDATED',
  AGENT_ACTION_COMPLETE: 'AGENT_ACTION_COMPLETE',
  SOCIAL_RELATION_CHANGED: 'SOCIAL_RELATION_CHANGED',
  COMBAT_ENGAGED: 'COMBAT_ENGAGED',
  RESOURCE_SPAWNED: 'RESOURCE_SPAWNED',
  AGENT_ACTION_COMMANDED: 'AGENT_ACTION_COMMANDED',
  AGENT_GOAL_CHANGED: 'AGENT_GOAL_CHANGED',
  DIVINE_BLESSING_GRANTED: 'DIVINE_BLESSING_GRANTED',
  GOVERNANCE_UPDATE: 'GOVERNANCE_UPDATE',
  GOVERNANCE_ACTION: 'GOVERNANCE_ACTION',
  ECONOMY_RESERVATIONS_UPDATE: 'ECONOMY_RESERVATIONS_UPDATE',
  HOUSEHOLD_HIGH_OCCUPANCY: 'HOUSEHOLD_HIGH_OCCUPANCY',
  HOUSEHOLD_AGENTS_HOMELESS: 'HOUSEHOLD_AGENTS_HOMELESS',
  HOUSEHOLD_NO_FREE_HOUSES: 'HOUSEHOLD_NO_FREE_HOUSES',
};
