/**
 * Event type enumerations for the simulation system.
 *
 * All game events are defined here as enums to ensure type safety
 * and prevent typos or inconsistencies in event names.
 *
 * @module shared/constants/EventEnums
 */

/**
 * Enumeration of all game event types.
 * These events are emitted by simulation systems and listened to by other systems.
 */
export enum GameEventType {
  RESOURCE_GATHERED = "RESOURCE_GATHERED",
  RESOURCE_SPAWNED = "RESOURCE_SPAWNED",
  RESOURCE_DEPLETED = "RESOURCE_DEPLETED",
  RESOURCE_STATE_CHANGE = "RESOURCE_STATE_CHANGE",
  RESOURCE_CONSUMED = "RESOURCE_CONSUMED",
  RESOURCE_DISCOVERED = "RESOURCE_DISCOVERED",
  RESOURCES_DEPOSITED = "RESOURCES_DEPOSITED",

  AGENT_BIRTH = "AGENT_BIRTH",
  AGENT_DEATH = "AGENT_DEATH",
  AGENT_AGED = "AGENT_AGED",
  AGENT_RESPAWNED = "AGENT_RESPAWNED",
  AGENT_ACTION_COMPLETE = "AGENT_ACTION_COMPLETE",
  AGENT_ACTION_COMMANDED = "AGENT_ACTION_COMMANDED",
  AGENT_GOAL_CHANGED = "AGENT_GOAL_CHANGED",
  AGENT_ACTIVITY_STARTED = "AGENT_ACTIVITY_STARTED",

  COMBAT_ENGAGED = "COMBAT_ENGAGED",
  COMBAT_HIT = "COMBAT_HIT",
  COMBAT_KILL = "COMBAT_KILL",
  COMBAT_WEAPON_EQUIPPED = "COMBAT_WEAPON_EQUIPPED",
  COMBAT_WEAPON_CRAFTED = "COMBAT_WEAPON_CRAFTED",

  BUILDING_CONSTRUCTION_STARTED = "BUILDING_CONSTRUCTION_STARTED",
  BUILDING_CONSTRUCTED = "BUILDING_CONSTRUCTED",
  BUILDING_DAMAGED = "BUILDING_DAMAGED",
  BUILDING_REPAIRED = "BUILDING_REPAIRED",

  PRODUCTION_OUTPUT_GENERATED = "PRODUCTION_OUTPUT_GENERATED",
  PRODUCTION_WORKER_REMOVED = "PRODUCTION_WORKER_REMOVED",
  CRAFTING_JOB_STARTED = "CRAFTING_JOB_STARTED",
  CRAFTING_JOB_COMPLETED = "CRAFTING_JOB_COMPLETED",
  ITEM_GENERATED = "ITEM_GENERATED",
  ITEM_COLLECTED = "ITEM_COLLECTED",
  ITEM_CRAFTED = "ITEM_CRAFTED",

  ANIMAL_SPAWNED = "ANIMAL_SPAWNED",
  ANIMAL_DIED = "ANIMAL_DIED",
  ANIMAL_HUNTED = "ANIMAL_HUNTED",
  ANIMAL_CONSUMED_RESOURCE = "ANIMAL_CONSUMED_RESOURCE",
  ANIMAL_REPRODUCED = "ANIMAL_REPRODUCED",

  SOCIAL_RELATION_CHANGED = "SOCIAL_RELATION_CHANGED",
  SOCIAL_TRUCE_IMPOSED = "SOCIAL_TRUCE_IMPOSED",
  SOCIAL_TRUCE_EXPIRED = "SOCIAL_TRUCE_EXPIRED",
  SOCIAL_RALLY = "SOCIAL_RALLY",
  SOCIAL_GROUPS_UPDATE = "SOCIAL_GROUPS_UPDATE",
  SOCIAL_INTERACTION = "SOCIAL_INTERACTION",
  FRIENDSHIP_FORMED = "FRIENDSHIP_FORMED",

  MOVEMENT_ARRIVED_AT_ZONE = "MOVEMENT_ARRIVED_AT_ZONE",
  MOVEMENT_ACTIVITY_COMPLETED = "MOVEMENT_ACTIVITY_COMPLETED",
  MOVEMENT_ACTIVITY_STARTED = "MOVEMENT_ACTIVITY_STARTED",
  PATHFINDING_FAILED = "PATHFINDING_FAILED",

  TRADE_OFFER_CREATED = "TRADE_OFFER_CREATED",
  TRADE_COMPLETED = "TRADE_COMPLETED",
  TRADE_REJECTED = "TRADE_REJECTED",

  MARRIAGE_PROPOSED = "MARRIAGE_PROPOSED",
  MARRIAGE_ACCEPTED = "MARRIAGE_ACCEPTED",
  MARRIAGE_REJECTED = "MARRIAGE_REJECTED",
  MARRIAGE_GROUP_FORMED = "MARRIAGE_GROUP_FORMED",
  MARRIAGE_MEMBER_JOINED = "MARRIAGE_MEMBER_JOINED",
  MARRIAGE_MEMBER_LEFT = "MARRIAGE_MEMBER_LEFT",
  DIVORCE_INITIATED = "DIVORCE_INITIATED",
  DIVORCE_COMPLETED = "DIVORCE_COMPLETED",
  WIDOWHOOD_REGISTERED = "WIDOWHOOD_REGISTERED",

  SALARY_PAID = "SALARY_PAID",
  ECONOMY_RESERVATIONS_UPDATE = "ECONOMY_RESERVATIONS_UPDATE",
  MONEY_CHANGED = "MONEY_CHANGED",
  MONEY_TRANSFERRED = "MONEY_TRANSFERRED",

  TERRAIN_MODIFIED = "TERRAIN_MODIFIED",
  TIME_WEATHER_CHANGED = "TIME_WEATHER_CHANGED",
  TIME_CHANGED = "TIME_CHANGED",

  LEGEND_UPDATE = "LEGEND_UPDATE",
  REPUTATION_UPDATED = "REPUTATION_UPDATED",

  GOVERNANCE_UPDATE = "GOVERNANCE_UPDATE",
  GOVERNANCE_ACTION = "GOVERNANCE_ACTION",

  HOUSEHOLD_HIGH_OCCUPANCY = "HOUSEHOLD_HIGH_OCCUPANCY",
  HOUSEHOLD_AGENTS_HOMELESS = "HOUSEHOLD_AGENTS_HOMELESS",
  HOUSEHOLD_NO_FREE_HOUSES = "HOUSEHOLD_NO_FREE_HOUSES",
  HOUSEHOLD_AGENT_ASSIGNED = "HOUSEHOLD_AGENT_ASSIGNED",
  HOUSEHOLD_AGENT_LEFT = "HOUSEHOLD_AGENT_LEFT",
  HOUSEHOLD_RESOURCE_DEPOSITED = "HOUSEHOLD_RESOURCE_DEPOSITED",
  HOUSEHOLD_RESOURCE_WITHDRAWN = "HOUSEHOLD_RESOURCE_WITHDRAWN",

  INTERACTION_GAME_PLAYED = "INTERACTION_GAME_PLAYED",

  REPRODUCTION_SUCCESS = "REPRODUCTION_SUCCESS",
  REPRODUCTION_ATTEMPT = "REPRODUCTION_ATTEMPT",

  INVENTORY_DROPPED = "INVENTORY_DROPPED",

  NEED_CRITICAL = "NEED_CRITICAL",
  NEED_SATISFIED = "NEED_SATISFIED",
  CRISIS_IMMEDIATE_WARNING = "CRISIS_IMMEDIATE_WARNING",

  KNOWLEDGE_LEARNED = "KNOWLEDGE_LEARNED",
  KNOWLEDGE_SHARED = "KNOWLEDGE_SHARED",
  KNOWLEDGE_ADDED = "KNOWLEDGE_ADDED",

  THREAT_DETECTED = "THREAT_DETECTED",

  TASK_CREATED = "TASK_CREATED",
  TASK_PROGRESS = "TASK_PROGRESS",
  TASK_COMPLETED = "TASK_COMPLETED",
  TASK_STALLED = "TASK_STALLED",

  QUEST_COMPLETED = "QUEST_COMPLETED",
  QUEST_STARTED = "QUEST_STARTED",
  QUEST_FAILED = "QUEST_FAILED",

  ROLE_ASSIGNED = "ROLE_ASSIGNED",
  ROLE_REASSIGNED = "ROLE_REASSIGNED",
  ROLE_SHIFT_CHANGED = "ROLE_SHIFT_CHANGED",
  ROLE_REBALANCED = "ROLE_REBALANCED",

  NORM_VIOLATED = "NORM_VIOLATED",
  NORM_SANCTION_APPLIED = "NORM_SANCTION_APPLIED",

  CONFLICT_TRUCE_PROPOSED = "CONFLICT_TRUCE_PROPOSED",
  CONFLICT_TRUCE_ACCEPTED = "CONFLICT_TRUCE_ACCEPTED",
  CONFLICT_TRUCE_REJECTED = "CONFLICT_TRUCE_REJECTED",
}

/**
 * Array containing all game event type values.
 * Used for iterating over all event types when setting up listeners.
 */
export const ALL_GAME_EVENT_TYPES: GameEventType[] =
  Object.values(GameEventType);
