/**
 * Event type enumerations for the simulation system.
 *
 * All game events are defined here as enums to ensure type safety
 * and prevent typos or inconsistencies in event names.
 *
 * @module shared/constants/EventEnums
 */

/**
 * Enumeration of all game event types.
 * These events are emitted by simulation systems and listened to by other systems.
 */
export enum GameEventType {
  RESOURCE_GATHERED = "RESOURCE_GATHERED",
  RESOURCE_SPAWNED = "RESOURCE_SPAWNED",
  RESOURCE_DEPLETED = "RESOURCE_DEPLETED",
  RESOURCE_STATE_CHANGE = "RESOURCE_STATE_CHANGE",
  RESOURCE_CONSUMED = "RESOURCE_CONSUMED",
  RESOURCE_DISCOVERED = "RESOURCE_DISCOVERED",
  RESOURCES_DEPOSITED = "RESOURCES_DEPOSITED",

  AGENT_BIRTH = "AGENT_BIRTH",
  AGENT_DEATH = "AGENT_DEATH",
  AGENT_AGED = "AGENT_AGED",
  AGENT_RESPAWNED = "AGENT_RESPAWNED",
  AGENT_ACTION_COMPLETE = "AGENT_ACTION_COMPLETE",
  AGENT_ACTION_COMMANDED = "AGENT_ACTION_COMMANDED",
  AGENT_GOAL_CHANGED = "AGENT_GOAL_CHANGED",
  AGENT_ACTIVITY_STARTED = "AGENT_ACTIVITY_STARTED",

  COMBAT_ENGAGED = "COMBAT_ENGAGED",
  COMBAT_HIT = "COMBAT_HIT",
  COMBAT_KILL = "COMBAT_KILL",
  COMBAT_WEAPON_EQUIPPED = "COMBAT_WEAPON_EQUIPPED",
  COMBAT_WEAPON_CRAFTED = "COMBAT_WEAPON_CRAFTED",

  BUILDING_CONSTRUCTION_STARTED = "BUILDING_CONSTRUCTION_STARTED",
  BUILDING_CONSTRUCTED = "BUILDING_CONSTRUCTED",
  BUILDING_DAMAGED = "BUILDING_DAMAGED",
  BUILDING_REPAIRED = "BUILDING_REPAIRED",

  PRODUCTION_OUTPUT_GENERATED = "PRODUCTION_OUTPUT_GENERATED",
  PRODUCTION_WORKER_REMOVED = "PRODUCTION_WORKER_REMOVED",
  CRAFTING_JOB_STARTED = "CRAFTING_JOB_STARTED",
  CRAFTING_JOB_COMPLETED = "CRAFTING_JOB_COMPLETED",
  ITEM_GENERATED = "ITEM_GENERATED",
  ITEM_COLLECTED = "ITEM_COLLECTED",
  ITEM_CRAFTED = "ITEM_CRAFTED",

  ANIMAL_SPAWNED = "ANIMAL_SPAWNED",
  ANIMAL_DIED = "ANIMAL_DIED",
  ANIMAL_HUNTED = "ANIMAL_HUNTED",
  ANIMAL_CONSUMED_RESOURCE = "ANIMAL_CONSUMED_RESOURCE",
  ANIMAL_REPRODUCED = "ANIMAL_REPRODUCED",

  SOCIAL_RELATION_CHANGED = "SOCIAL_RELATION_CHANGED",
  SOCIAL_TRUCE_IMPOSED = "SOCIAL_TRUCE_IMPOSED",
  SOCIAL_TRUCE_EXPIRED = "SOCIAL_TRUCE_EXPIRED",
  SOCIAL_RALLY = "SOCIAL_RALLY",
  SOCIAL_GROUPS_UPDATE = "SOCIAL_GROUPS_UPDATE",
  SOCIAL_INTERACTION = "SOCIAL_INTERACTION",
  FRIENDSHIP_FORMED = "FRIENDSHIP_FORMED",
  RELATIONSHIP_ENDED = "RELATIONSHIP_ENDED",

  MOVEMENT_ARRIVED_AT_ZONE = "MOVEMENT_ARRIVED_AT_ZONE",
  MOVEMENT_ACTIVITY_COMPLETED = "MOVEMENT_ACTIVITY_COMPLETED",
  MOVEMENT_ACTIVITY_STARTED = "MOVEMENT_ACTIVITY_STARTED",
  PATHFINDING_FAILED = "PATHFINDING_FAILED",

  DIALOGUE_SHOW_CARD = "DIALOGUE_SHOW_CARD",
  DIALOGUE_CARD_EXPIRED = "DIALOGUE_CARD_EXPIRED",
  DIALOGUE_CARD_RESPONDED = "DIALOGUE_CARD_RESPONDED",

  APPEARANCE_GENERATED = "APPEARANCE_GENERATED",
  APPEARANCE_UPDATED = "APPEARANCE_UPDATED",

  TRADE_OFFER_CREATED = "TRADE_OFFER_CREATED",
  TRADE_COMPLETED = "TRADE_COMPLETED",
  TRADE_REJECTED = "TRADE_REJECTED",

  MARRIAGE_PROPOSED = "MARRIAGE_PROPOSED",
  MARRIAGE_ACCEPTED = "MARRIAGE_ACCEPTED",
  MARRIAGE_REJECTED = "MARRIAGE_REJECTED",
  MARRIAGE_GROUP_FORMED = "MARRIAGE_GROUP_FORMED",
  MARRIAGE_MEMBER_JOINED = "MARRIAGE_MEMBER_JOINED",
  MARRIAGE_MEMBER_LEFT = "MARRIAGE_MEMBER_LEFT",
  DIVORCE_INITIATED = "DIVORCE_INITIATED",
  DIVORCE_COMPLETED = "DIVORCE_COMPLETED",
  WIDOWHOOD_REGISTERED = "WIDOWHOOD_REGISTERED",

  SALARY_PAID = "SALARY_PAID",
  ECONOMY_RESERVATIONS_UPDATE = "ECONOMY_RESERVATIONS_UPDATE",
  MONEY_CHANGED = "MONEY_CHANGED",
  MONEY_TRANSFERRED = "MONEY_TRANSFERRED",

  CRISIS_PREDICTION = "CRISIS_PREDICTION",
  CRISIS_IMMEDIATE_WARNING = "CRISIS_IMMEDIATE_WARNING",

  CHUNK_RENDERED = "CHUNK_RENDERED",
  TERRAIN_MODIFIED = "TERRAIN_MODIFIED",
  TIME_CHANGED = "TIME_CHANGED",
  TIME_WEATHER_CHANGED = "TIME_WEATHER_CHANGED",

  LEGEND_UPDATE = "LEGEND_UPDATE",
  REPUTATION_UPDATED = "REPUTATION_UPDATED",

  GOVERNANCE_UPDATE = "GOVERNANCE_UPDATE",
  GOVERNANCE_ACTION = "GOVERNANCE_ACTION",

  HOUSEHOLD_HIGH_OCCUPANCY = "HOUSEHOLD_HIGH_OCCUPANCY",
  HOUSEHOLD_AGENTS_HOMELESS = "HOUSEHOLD_AGENTS_HOMELESS",
  HOUSEHOLD_NO_FREE_HOUSES = "HOUSEHOLD_NO_FREE_HOUSES",
  HOUSEHOLD_AGENT_ASSIGNED = "HOUSEHOLD_AGENT_ASSIGNED",
  HOUSEHOLD_AGENT_LEFT = "HOUSEHOLD_AGENT_LEFT",
  HOUSEHOLD_RESOURCE_DEPOSITED = "HOUSEHOLD_RESOURCE_DEPOSITED",
  HOUSEHOLD_RESOURCE_WITHDRAWN = "HOUSEHOLD_RESOURCE_WITHDRAWN",

  EMERGENCE_METRICS_UPDATED = "EMERGENCE_METRICS_UPDATED",
  EMERGENCE_PATTERN_DETECTED = "EMERGENCE_PATTERN_DETECTED",

  INTERACTION_GAME_PLAYED = "INTERACTION_GAME_PLAYED",

  REPRODUCTION_SUCCESS = "REPRODUCTION_SUCCESS",
  REPRODUCTION_ATTEMPT = "REPRODUCTION_ATTEMPT",

  INVENTORY_DROPPED = "INVENTORY_DROPPED",

  NEED_CRITICAL = "NEED_CRITICAL",
  NEED_SATISFIED = "NEED_SATISFIED",

  KNOWLEDGE_LEARNED = "KNOWLEDGE_LEARNED",
  KNOWLEDGE_SHARED = "KNOWLEDGE_SHARED",
  KNOWLEDGE_ADDED = "KNOWLEDGE_ADDED",

  THREAT_DETECTED = "THREAT_DETECTED",

  DIVINE_BLESSING_GRANTED = "DIVINE_BLESSING_GRANTED",

  TASK_CREATED = "TASK_CREATED",
  TASK_PROGRESS = "TASK_PROGRESS",
  TASK_COMPLETED = "TASK_COMPLETED",
  TASK_STALLED = "TASK_STALLED",

  QUEST_COMPLETED = "QUEST_COMPLETED",
  QUEST_STARTED = "QUEST_STARTED",
  QUEST_FAILED = "QUEST_FAILED",

  ROLE_ASSIGNED = "ROLE_ASSIGNED",
  ROLE_REASSIGNED = "ROLE_REASSIGNED",
  ROLE_SHIFT_CHANGED = "ROLE_SHIFT_CHANGED",
  ROLE_REBALANCED = "ROLE_REBALANCED",

  NORM_VIOLATED = "NORM_VIOLATED",
  NORM_SANCTION_APPLIED = "NORM_SANCTION_APPLIED",

  CONFLICT_TRUCE_PROPOSED = "CONFLICT_TRUCE_PROPOSED",
  CONFLICT_TRUCE_ACCEPTED = "CONFLICT_TRUCE_ACCEPTED",
  CONFLICT_TRUCE_REJECTED = "CONFLICT_TRUCE_REJECTED",
}

/**
 * Type representing all possible game event type values.
 */
export type GameEventTypeValue = `${GameEventType}`;

/**
 * Legacy object for backward compatibility.
 * Maps event names to their string values.
 * @deprecated Use GameEventType enum instead
 */
export const GameEventNames = {
  RESOURCE_GATHERED: GameEventType.RESOURCE_GATHERED,
  CHUNK_RENDERED: GameEventType.CHUNK_RENDERED,
  RESOURCE_STATE_CHANGE: GameEventType.RESOURCE_STATE_CHANGE,
  LEGEND_UPDATE: GameEventType.LEGEND_UPDATE,
  REPUTATION_UPDATED: GameEventType.REPUTATION_UPDATED,
  AGENT_ACTION_COMPLETE: GameEventType.AGENT_ACTION_COMPLETE,
  SOCIAL_RELATION_CHANGED: GameEventType.SOCIAL_RELATION_CHANGED,
  COMBAT_ENGAGED: GameEventType.COMBAT_ENGAGED,
  COMBAT_HIT: GameEventType.COMBAT_HIT,
  COMBAT_KILL: GameEventType.COMBAT_KILL,
  COMBAT_WEAPON_EQUIPPED: GameEventType.COMBAT_WEAPON_EQUIPPED,
  COMBAT_WEAPON_CRAFTED: GameEventType.COMBAT_WEAPON_CRAFTED,
  RESOURCE_SPAWNED: GameEventType.RESOURCE_SPAWNED,
  RESOURCE_DEPLETED: GameEventType.RESOURCE_DEPLETED,
  AGENT_ACTION_COMMANDED: GameEventType.AGENT_ACTION_COMMANDED,
  AGENT_GOAL_CHANGED: GameEventType.AGENT_GOAL_CHANGED,
  DIVINE_BLESSING_GRANTED: GameEventType.DIVINE_BLESSING_GRANTED,
  GOVERNANCE_UPDATE: GameEventType.GOVERNANCE_UPDATE,
  GOVERNANCE_ACTION: GameEventType.GOVERNANCE_ACTION,
  ECONOMY_RESERVATIONS_UPDATE: GameEventType.ECONOMY_RESERVATIONS_UPDATE,
  BUILDING_CONSTRUCTION_STARTED: GameEventType.BUILDING_CONSTRUCTION_STARTED,
  BUILDING_CONSTRUCTED: GameEventType.BUILDING_CONSTRUCTED,
  BUILDING_DAMAGED: GameEventType.BUILDING_DAMAGED,
  BUILDING_REPAIRED: GameEventType.BUILDING_REPAIRED,
  PRODUCTION_OUTPUT_GENERATED: GameEventType.PRODUCTION_OUTPUT_GENERATED,
  PRODUCTION_WORKER_REMOVED: GameEventType.PRODUCTION_WORKER_REMOVED,
  CRAFTING_JOB_STARTED: GameEventType.CRAFTING_JOB_STARTED,
  CRAFTING_JOB_COMPLETED: GameEventType.CRAFTING_JOB_COMPLETED,
  ANIMAL_SPAWNED: GameEventType.ANIMAL_SPAWNED,
  ANIMAL_DIED: GameEventType.ANIMAL_DIED,
  ANIMAL_HUNTED: GameEventType.ANIMAL_HUNTED,
  TERRAIN_MODIFIED: GameEventType.TERRAIN_MODIFIED,
  ANIMAL_CONSUMED_RESOURCE: GameEventType.ANIMAL_CONSUMED_RESOURCE,
  ANIMAL_REPRODUCED: GameEventType.ANIMAL_REPRODUCED,
  ITEM_GENERATED: GameEventType.ITEM_GENERATED,
  ITEM_COLLECTED: GameEventType.ITEM_COLLECTED,
  HOUSEHOLD_HIGH_OCCUPANCY: GameEventType.HOUSEHOLD_HIGH_OCCUPANCY,
  HOUSEHOLD_AGENTS_HOMELESS: GameEventType.HOUSEHOLD_AGENTS_HOMELESS,
  HOUSEHOLD_NO_FREE_HOUSES: GameEventType.HOUSEHOLD_NO_FREE_HOUSES,
  HOUSEHOLD_AGENT_ASSIGNED: GameEventType.HOUSEHOLD_AGENT_ASSIGNED,
  HOUSEHOLD_AGENT_LEFT: GameEventType.HOUSEHOLD_AGENT_LEFT,
  HOUSEHOLD_RESOURCE_DEPOSITED: GameEventType.HOUSEHOLD_RESOURCE_DEPOSITED,
  HOUSEHOLD_RESOURCE_WITHDRAWN: GameEventType.HOUSEHOLD_RESOURCE_WITHDRAWN,
  TIME_CHANGED: GameEventType.TIME_CHANGED,
  TIME_WEATHER_CHANGED: GameEventType.TIME_WEATHER_CHANGED,
  EMERGENCE_METRICS_UPDATED: GameEventType.EMERGENCE_METRICS_UPDATED,
  EMERGENCE_PATTERN_DETECTED: GameEventType.EMERGENCE_PATTERN_DETECTED,
  INTERACTION_GAME_PLAYED: GameEventType.INTERACTION_GAME_PLAYED,
  SOCIAL_GROUPS_UPDATE: GameEventType.SOCIAL_GROUPS_UPDATE,
  SOCIAL_RALLY: GameEventType.SOCIAL_RALLY,
  SOCIAL_TRUCE_IMPOSED: GameEventType.SOCIAL_TRUCE_IMPOSED,
  SOCIAL_TRUCE_EXPIRED: GameEventType.SOCIAL_TRUCE_EXPIRED,
  SOCIAL_INTERACTION: GameEventType.SOCIAL_INTERACTION,
  FRIENDSHIP_FORMED: GameEventType.FRIENDSHIP_FORMED,
  RELATIONSHIP_ENDED: GameEventType.RELATIONSHIP_ENDED,
  DIALOGUE_SHOW_CARD: GameEventType.DIALOGUE_SHOW_CARD,
  DIALOGUE_CARD_EXPIRED: GameEventType.DIALOGUE_CARD_EXPIRED,
  APPEARANCE_GENERATED: GameEventType.APPEARANCE_GENERATED,
  APPEARANCE_UPDATED: GameEventType.APPEARANCE_UPDATED,
  AGENT_BIRTH: GameEventType.AGENT_BIRTH,
  AGENT_DEATH: GameEventType.AGENT_DEATH,
  AGENT_AGED: GameEventType.AGENT_AGED,
  AGENT_RESPAWNED: GameEventType.AGENT_RESPAWNED,
  REPRODUCTION_SUCCESS: GameEventType.REPRODUCTION_SUCCESS,
  REPRODUCTION_ATTEMPT: GameEventType.REPRODUCTION_ATTEMPT,
  INVENTORY_DROPPED: GameEventType.INVENTORY_DROPPED,
  NEED_CRITICAL: GameEventType.NEED_CRITICAL,
  NEED_SATISFIED: GameEventType.NEED_SATISFIED,
  RESOURCE_CONSUMED: GameEventType.RESOURCE_CONSUMED,
  AGENT_ACTIVITY_STARTED: GameEventType.AGENT_ACTIVITY_STARTED,
  RESOURCES_DEPOSITED: GameEventType.RESOURCES_DEPOSITED,
  ITEM_CRAFTED: GameEventType.ITEM_CRAFTED,
  MOVEMENT_ARRIVED_AT_ZONE: GameEventType.MOVEMENT_ARRIVED_AT_ZONE,
  MOVEMENT_ACTIVITY_COMPLETED: GameEventType.MOVEMENT_ACTIVITY_COMPLETED,
  MOVEMENT_ACTIVITY_STARTED: GameEventType.MOVEMENT_ACTIVITY_STARTED,
  PATHFINDING_FAILED: GameEventType.PATHFINDING_FAILED,
  DIALOGUE_CARD_RESPONDED: GameEventType.DIALOGUE_CARD_RESPONDED,
  KNOWLEDGE_LEARNED: GameEventType.KNOWLEDGE_LEARNED,
  KNOWLEDGE_SHARED: GameEventType.KNOWLEDGE_SHARED,
  KNOWLEDGE_ADDED: GameEventType.KNOWLEDGE_ADDED,
  RESOURCE_DISCOVERED: GameEventType.RESOURCE_DISCOVERED,
  THREAT_DETECTED: GameEventType.THREAT_DETECTED,
  SALARY_PAID: GameEventType.SALARY_PAID,
  MONEY_CHANGED: GameEventType.MONEY_CHANGED,
  MONEY_TRANSFERRED: GameEventType.MONEY_TRANSFERRED,
  TRADE_OFFER_CREATED: GameEventType.TRADE_OFFER_CREATED,
  TRADE_COMPLETED: GameEventType.TRADE_COMPLETED,
  TRADE_REJECTED: GameEventType.TRADE_REJECTED,
  MARRIAGE_PROPOSED: GameEventType.MARRIAGE_PROPOSED,
  MARRIAGE_ACCEPTED: GameEventType.MARRIAGE_ACCEPTED,
  MARRIAGE_REJECTED: GameEventType.MARRIAGE_REJECTED,
  MARRIAGE_GROUP_FORMED: GameEventType.MARRIAGE_GROUP_FORMED,
  MARRIAGE_MEMBER_JOINED: GameEventType.MARRIAGE_MEMBER_JOINED,
  MARRIAGE_MEMBER_LEFT: GameEventType.MARRIAGE_MEMBER_LEFT,
  DIVORCE_INITIATED: GameEventType.DIVORCE_INITIATED,
  DIVORCE_COMPLETED: GameEventType.DIVORCE_COMPLETED,
  WIDOWHOOD_REGISTERED: GameEventType.WIDOWHOOD_REGISTERED,
  CRISIS_PREDICTION: GameEventType.CRISIS_PREDICTION,
  CRISIS_IMMEDIATE_WARNING: GameEventType.CRISIS_IMMEDIATE_WARNING,
  TASK_CREATED: GameEventType.TASK_CREATED,
  TASK_PROGRESS: GameEventType.TASK_PROGRESS,
  TASK_COMPLETED: GameEventType.TASK_COMPLETED,
  TASK_STALLED: GameEventType.TASK_STALLED,
  QUEST_COMPLETED: GameEventType.QUEST_COMPLETED,
  QUEST_STARTED: GameEventType.QUEST_STARTED,
  QUEST_FAILED: GameEventType.QUEST_FAILED,
  ROLE_ASSIGNED: GameEventType.ROLE_ASSIGNED,
  ROLE_REASSIGNED: GameEventType.ROLE_REASSIGNED,
  ROLE_SHIFT_CHANGED: GameEventType.ROLE_SHIFT_CHANGED,
  ROLE_REBALANCED: GameEventType.ROLE_REBALANCED,
  NORM_VIOLATED: GameEventType.NORM_VIOLATED,
  NORM_SANCTION_APPLIED: GameEventType.NORM_SANCTION_APPLIED,
  CONFLICT_TRUCE_PROPOSED: GameEventType.CONFLICT_TRUCE_PROPOSED,
  CONFLICT_TRUCE_ACCEPTED: GameEventType.CONFLICT_TRUCE_ACCEPTED,
  CONFLICT_TRUCE_REJECTED: GameEventType.CONFLICT_TRUCE_REJECTED,
} as const;
